global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'airflow-webserver'
    metrics_path: /metrics
    static_configs:
      - targets: ['airflow-webserver:8080']  # ✅ Имя сервиса в docker network
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']